name: Genart thingies

env: 
  GENART_APPLICABLE_BRANCH: feature/actions-testing
  AWS_ACCOUNT_ID: 901024526765


on: 
  push: 
    branches:
      - feature/actions-testing
jobs: 
  buildin: 
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2

      - name: Login to AWS
        run: | 
          aws --version
          mkdir ~/.aws
          touch ~/.aws/credentials ~/.aws/config
          
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{secrets.AWS_ACCESS_KEY_ID}}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{secrets.AWS_SECRET_ACCESS_KEY}}" >> ~/.aws/credentials

          echo "[default]" >> ~/.aws/config
          echo "region=us-east-1" >> ~/.aws/config
          echo "output=json" >> ~/.aws/config

          
      - name: Login to ECR
        run: |
          echo $AWS_ACCOUNT_ID
          AWS_ECR_PW=$(aws ecr get-login-password --region us-east-1)
          echo $AWS_ECR_PW | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
        
      - name: Build Image
        run: docker build -t genart .

      - name: Verify Build
        run: |
          echo Here is the info:
          docker images --filter reference=genart

      - name: Do some tests n shit
        run: |
          echo There arent any tests now
          echo Deal with it.

      - name: Tag n' push
        run: |
          docker tag genart:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/genart:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/genart:latest


