name: CD Biz

env: 
  MF_APPLICABLE_BRANCH: feature/actions-testing
  AWS_ACCOUNT_ID: 901024526765

on: 
  push: #in the future we test for tags and leave the branch testing for later
    branches:
      - feature/actions-testing
jobs: 
  buildin: 
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Set Tag
        run: |
          export TAG=$(git describe --tags)
          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            echo We have an acceptable version tag to use
          else
            echo No acceptable version tag, using \"latest\"
            export TAG=latest
          fi
          echo Current Image Tag will be: $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV 

      - name: Set AWS Creds
        run: |
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION=us-east-1

      # - name: Configure AWS Credentials for BUILD
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{secrets.MF_DEV_GITHUB_ACTION_AWS_ACCESS_KEY_ID}}
      #     aws-secret-access-key: ${{secrets.MF_DEV_GITHUB_ACTION_AWS_SECRET_ACCESS_KEY}}
      #     aws-region: us-east-1
      #     mask-aws-account-id: true
          
      # - name: Login to Amazon ECR
      #   id: login-build-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: Login to ECR
        run: |
          AWS_ECR_PW=$(aws ecr get-login-password --region us-east-1)
          echo $AWS_ECR_PW | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com

      - name: Show AWS Identity
        run: aws sts get-caller-identity
        
      # - name: Build Base Image
      #   run: |
      #     cat > pip.conf <<EOF
      #     ${{secrets.MF_GITHUB_ACTION_PIP_CONFIG}}
      #     EOF
      #     docker build -t mfpartnumberbase -f Dockerfiles/MFPartNumberBase .

      # - name: Build Microservice Image
      #   env: 
      #     TAG: ${{env.TAG}}
      #   # run: make container # don't do this bc ../Makeinclude isn't checkedout on the Github runner
      #   run: |
      #     echo Tag is $TAG just in case
      #     docker build -t mfpartnumber-testing:$TAG -f Dockerfiles/MFPartNumber .

      - name: Build Image
        run: |
          docker build -t genart:$TAG . 

      - name: Verify Build
        run: |
          echo Here is the info:
          docker images --filter reference=mfpartnumber-testing
      - name: Do some tests n shit
        run: |
          echo There arent any tests now
          echo Deal with it.
      
      - name: Tag n' push
        run: |
          docker tag genart:$TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/genart:$TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/genart:$TAG

      - name: Logout of ECR
        run: docker logout $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
        