name: Build Genart

env: 
  GENART_APPLICABLE_BRANCH: feature/actions-testing
  AWS_ACCOUNT_ID: 901024526765


on: 
  push: 
    branches:
      - ${{env.GENART_APPLICABLE_BRANCH}}

jobs: 
  buildin: 
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
        
      - name: Build Image
        run: docker build -t genart .

      - name: Verify Build
        run: |
          echo 'Here\'s the info:'
          docker images --filter reference=genart

      - name: Do some tests n shit
        run: |
          echo 'There aren\'t any tests now'
          echo 'Deal with it.'
          
      - name: Login to ECR
        run: |
          AWS_ECR_PW=$(aws ecr get-login-password --region us-east-1)
          echo $AWS_ECR_PW | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag n' push
        run: |
          docker tag genart:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/genart:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/genart:latest


