name: PR Testing

env: 
  
  AWS_ACCOUNT_ID: 901024526765
  

on: 
  pull_request: 
    branches: [feature/actions-testing]

jobs: 
  Testing: 
    runs-on: ubuntu-20.04
    steps: 
      
      - uses: actions/checkout@v2
        name: Checkout current repo
        with:
          path: main

      - uses: actions/checkout@v2
        name: Checkout Make Scripts
        with: 
          repository: MacroFab/Makeinclude
          path: MakeInclude
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      # - name: Run Make Container
      #   run: | 
      #     cd main
      #     make container

      - name: Run Unit Tests
        # Tests aren't working right now so we'll just export some placeholder results
        run: |
          GRADE=100
          echo CODE_COVERAGE_GRADE=${GRADE} >> $GITHUB_ENV
          if [[$GRADE -ge 90]]
          then 
            COLOR=green
          elif [[$GRADE -ge 80]]
          then
            COLOR=yellow
          else 
            COLOR=red
          fi
          echo CODE_COVERAGE_COLOR=${COLOR} >> $GITHUB_ENV

      - name: Generate Comment
        run: | 
          cat > comment.json <<SCIBBITYBOOBOP
          {
            "body": 
            "## Code Coverage Report: \n
            ![Coverage Badge](https://img.shields.io/badge/coverage-${{env.CODE_COVERAGE_GRADE}}%25-${{env.CODE_COVERAGE_COLOR}})"
          }
          SCIBBITYBOOBOP

      - name: Post Comment
        run: |
          curl -X POST "https://api.github.com/repos/${{github.repository}}/issues/${{github.event.number}}/comments" \
          -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
          -H "Content-Type: application/json" \
          -d "@comment.json"