name: PR Testing

env: 
  
  AWS_ACCOUNT_ID: 901024526765
  

on: 
  pull_request: 
    branches: [feature/actions-testing]

jobs: 
  Testing: 
    runs-on: ubuntu-20.04
    steps: 
      
      - uses: actions/checkout@v2
        name: Checkout current repo
        with:
          path: main

      - uses: actions/checkout@v2
        name: Checkout Make Scripts
        with: 
          repository: MacroFab/Makeinclude
          path: MakeInclude
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      # - name: Run Make Container
      #   run: | 
      #     cd main
      #     make container


      - name: Check Issue number
        run: echo ${{github.event.issue.number}}

      - name: Make Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        with: 
          issue-number: ${{github.event.issue.number}}
          body: | 
            # This is some **Markdown** stuff
            ## Just a smaller header for testing
            Lets see how code coverage did: 
            ![Coverage Badge](https://img.shields.io/badge/coverage-100%-green)