name: PR Testing

env: 
  
  AWS_ACCOUNT_ID: 901024526765
  

on: 
  pull_request: 
    branches: [feature/actions-testing]

jobs: 
  Testing: 
    runs-on: ubuntu-20.04
    steps: 
      
      - uses: actions/checkout@v2
        name: Checkout current repo

      - uses: actions/checkout@v2
        name: Checkout Make Scripts
        with: 
          repository: MacroFab/Makeinclude
          path: ../MakeInclude
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      # - name: Run Make Container
      #   run: | 
      #     cd main
      #     make container

      - name: Snoop around
        run: |
          ls -a
          ls -a $GITHUB_WORKSPACE
          ls -a ..